user  nginx;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

# spin up one worker per CPU core
worker_processes  auto;
# configures how Nginx handles network connections
# each worker can handle up to x connections at once
events { worker_connections 1024; }

http {

    # tells Nginx to load a mapping of file extensions → MIME types
    # Allows Nginx to automatically send the correct Content-Type header for a file
    # Without this, Nginx wouldn't know what type of file it's serving
    include       /etc/nginx/mime.types;
    # sets the default MIME type to use when Nginx can’t figure it out from the file extension
    # `application/octet-stream` is a generic binary type, meaning “I don’t know the file type, treat as raw data.”
    # The browser will usually just download the file rather than trying to render it
    default_type  application/octet-stream;

    log_format main
        '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
    log_format ssl_mismatch
        '$remote_addr - $remote_user [$time_local] - Plain HTTP on HTTPS port: "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';

    map $ssl_protocol $http_request {
        ""       1;  # No SSL → plaintext
        default  0;  # Any SSL version → valid HTTPS
    }

    # Normally NginX serves static files (eg HTML) by reading into memory and writing to network socket.
    # `sendfile on` transfers file directly from disk to network socket
    sendfile on;

    # Enable per-site logs
    access_log /var/log/nginx/access.log main;
    access_log /var/log/nginx/access-ssl-mismatch.log ssl_mismatch if=$http_request;

    include /etc/nginx/sites-enabled/*.conf;

}
