spring:
  application:
    name: chatterbox-api

  # Allows for ANSI additions, particularly to the banner.txt
  output:
    ansi:
      enabled: ALWAYS
  banner:
    location: banners-coloured/banner-chatterbox-colour-003.txt

common:
  logging:
    appender:
      file:
        location: /var/log/chatterbox-api

server:
  port: 1234
  address: 0.0.0.0   # must be 0.0.0.0 for Docker networking

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: "never"
    prometheus:
      access: unrestricted

packages:
  separate:
    logging:
      level: za.co.psybergate.chatterbox

chatterbox:
  sources:
    github:
      repository:
        destination-mapping:
          - name: Psybergate-Knowledge-Repository/mentoring_software_foundations
            teamsDestinationChannel: TestChannel
          - name: psyAlexBlakeGoudemond/chatterbox
            teamsDestinationChannel: TestChannel
      payload:
        event-mapping:
          push:
            displayName: "Push Event"
            fields:
              repositoryName: "repository.full_name"
              senderName: "sender.login"
              url: "issue.html_url"
              urlDisplayText: "head_commit.message"
          pull_request:
            displayName: "Pull Request Event"
            fields:
              repositoryName: "repository.full_name"
              senderName: "pull_request.user.login"
              url: "pull_request.html_url"
              urlDisplayText: "pull_request.title"
          poll_commit:
            displayName: "Commit Event"
            fields:
              repositoryName: "full_name"
              senderName: "commit.author.name"
              url: "commit.url"
              urlDisplayText: "commit.message" #
          poll_pull_request:
            displayName: "Pull Request Event"
            fields:
              repositoryName: "full_name"
              senderName: "user.login"
              url: "html_url"
              urlDisplayText: "title"
  destinations:
    teams:
      accepted-channel:
        - channelName: "General"
          webhookUrl: "https://outlook.office.com/webhook/..."
        - channelName: "TestChannel"
          webhookUrl: "https://outlook.office.com/webhook/..."
  deliveries:
    teams:
      adaptive-card-definition:
        type: "message"
        attachments:
          - contentType: "application/vnd.microsoft.card.adaptive"
            content:
              type: "AdaptiveCard"
              version: "1.0"
              msteams:
                width: Full
              body:
                - type: "TextBlock"
                  text: "📢 ${displayName} for ${repositoryName}"
                  wrap: true
                - type: "TextBlock"
                  text: "⁉️ Details: [${urlDisplayText}](${url}) created by ${senderName}"
                  wrap: true
  security:
    webhook:
      github:
        secret: secret
    api:
      github:
        token: "github_pat_123abc"
  api:
    prefix: /api
