spring:
  application:
    name: chatterbox-api

api:
  prefix: /api

common:
  logging:
    appender:
      file:
        location: /var/log/chatterbox-api

server:
  port: 1234
  address: 0.0.0.0   # must be 0.0.0.0 for Docker networking

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: "never"

packages:
  separate:
    logging:
      level: za.co.psybergate.chatterbox

webhook:
  github:
    secret: secret
