server {
    listen 80;
    server_name chatterbox;

    location /chatterbox/github {
        proxy_pass http://chatterbox:8080/api/webhook/github;  # Docker container is reachable on localhost
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Hub-Signature $http_x_hub_signature;
        proxy_set_header X-Hub-Signature-256 $http_x_hub_signature_256;
    }
}
